name: rna-seq-star-htseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - entrez-direct
  - htseq
  - parallel-fastq-dump
  - perl-parallel-forkmanager
  - perl-text-csv
  - perl-unix-processors
  - sra-tools
  - star
