name: rna-seq-star-htseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - entrez-direct
  - htseq
  - parallel-fastq-dump
  - perl-config-tiny
  - perl-ipc-system-simple
  - perl-parallel-forkmanager
  - perl-text-csv
  - perl-unix-processors
  - sra-tools
  - star
